### ISSUE TITLE
AttributeError: module 'qrcode' has no attribute 'constants'

### ISSUE THREAD

**Issue by dillibk777** [marcoagner/Flask-QRcode#28]
Hi, this module is really awesome. It is working fine normally but, when it tried to deploy it in server im getting the below error.
`Traceback (most recent call last):
  File "invoice.py", line 20, in <module>
    from flask_qrcode import QRcode
  File "/root/mydukan-invoicing-apis/venv/lib/python3.6/site-packages/flask_qrcode/__init__.py", line 35, in <module>
    class QRcode(object):
  File "/root/mydukan-invoicing-apis/venv/lib/python3.6/site-packages/flask_qrcode/__init__.py", line 43, in QRcode
    'L': qrc.constants.ERROR_CORRECT_L,
AttributeError: module 'qrcode' has no attribute 'constants'
(venv) [root@e2e-36-220 mydukan-invoicing-apis]# ^C
(venv) [root@e2e-36-220 mydukan-invoicing-apis]# python invoice.py
Traceback (most recent call last):
  File "invoice.py", line 20, in <module>
    from flask_qrcode import QRcode
  File "/root/mydukan-invoicing-apis/venv/lib/python3.6/site-packages/flask_qrcode/__init__.py", line 35, in <module>
    class QRcode(object):
  File "/root/mydukan-invoicing-apis/venv/lib/python3.6/site-packages/flask_qrcode/__init__.py", line 43, in QRcode
    'L': qrc.constants.ERROR_CORRECT_L,
AttributeError: module 'qrcode' has no attribute 'constants'`

**Comment by marcoagner** [comment]
Hi, @dillibk777. Could you confirm if you have a file named `qrcode.py`or a directory called `qrcode` as a module in the same directory? One of those situations could be causing the error.

If that's confirmed, the solution is to have your file/directory renamed to not cause this problem.

For the file case, the troubled project could look like this:
```
.
├── main.py
└── qrcode.py <--- This file must be renamed.
```

As for the directory case, it could look like this:

```
.
├── main.py
└── qrcode <--- This directory must be renamed.
    └── __init__.py
```

**Comment by dillibk777** [comment]
Hello @marcoagner , no i don't any file like that. That error is coming from the library only. And i've attached the same library code were the error is coming from,
`
class QRcode(object):
    """QR Code image class"""

    color = ['red', 'maroon', 'olive', 'yellow', 'lime', 'green',
             'aqua', 'teal', 'blue', 'navy', 'fuchsia', 'purple',
             'white', 'silver', 'gray', 'black']

    correction_levels = {
        'L': qrc.constants.ERROR_CORRECT_L,
        'M': qrc.constants.ERROR_CORRECT_M,
        'Q': qrc.constants.ERROR_CORRECT_Q,
        'H': qrc.constants.ERROR_CORRECT_H
    }
`
